#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/tmp
leaderip=` echo $@ | awk '{print $1}'`;
pool=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $3}'`;
privilege="DiskGroups";
echo hi=$privilege > /root/tmp2
contrun=`./privthis.sh $privilege $userreq`;
echo hi=$contrun >> /root/tmp2
echo $contrun | grep 'true'
if [ $? -eq 0  ]
then
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
echo iam in >> /root/tmp2
 waiting=1
 waitingc=1
 while [ $waiting -eq 1 ];
 do
  echo to frst while >> /root/tmp2
  currentreq=`/pace/etcdget.py $leaderip requests/DGdestroypool --prefix`'currentreq'
  echo currentre=$currentreq  >> /root/tmp2
  echo $currentreq | grep $myhost
  if [ $? -ne 0 ];
  then
  echo to continue >> /root/tmp2
   break
  fi
  echo to continue 0 >> /root/tmp2
  waitingc=$((waitingc+1))
  echo to continue 1, $waitingc >> /root/tmp2
  if [ $waitingc -eq 20 ];
  then
   echo to continue 2 >> /root/tmp2
   break
  fi
   echo to continue 3 >> /root/tmp2
  sleep 1
 done
 echo Iam her2 >> /root/tmp2
 zpool status | grep $pool 
 if [ $? -ne 0 ];
 then
  exit
 fi
 /pace/etcdput.py $leaderip requests/DGdestroypool/$myhost $myhost/$userreq
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq 
 docker exec etcdclient /TopStor/logmsg.py DGst5 info $userreq $pool
 waiting=1
 while [ $waiting -eq 1 ];
 do
  sleep 1
  pgrep zpool
  if [ $? -ne 0 ];
  then
   waiting=0
  fi
 done
 echo iam here2 >> /root/tmp2
 /sbin/zpool export -f $pool
 sleep 1
 /sbin/zpool import $pool
 sleep 1
 /sbin/zpool destroy -f $pool 2>/root/dgdestroyerror
 if [ $? -ne 0 ]; then
   docker exec etcdclient /TopStor/logmsg.py DGfa5 error $userreq $pool
 else
  stamp=`date +%s`
  ETCDCTL_API=3 /pace/etcddel.py $leaderip ActPools/$pool 
  ETCDCTL_API=3 /pace/etcddel.py $leaderip sync/ActPool/ ${pool} 
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/ActPool/Del_${pool}_$guid/request actpools_$stamp 
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/ActPool/Del_${pool}_$guid/request/$leader actpools_$stamp 
  ETCDCTL_API=3 /pace/etcddel.py $leaderip pools $pool
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/pools/Del_pools_${pool}/request pools_$stamp 
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/pools/Del_pools_${pool}/request/$leader pools_$stamp
  #ETCDCTL_API=3 /TopStor/deltolocal.py pools $pool
  ETCDCTL_API=3 /pace/etcddel.py $leaderip fixpool/$pool
  ETCDCTL_API=3 /pace/etcddel.py $leaderip activepool/$pool 
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/activepool/Del_activepool::${pool}_--prefix/request activepool_$stamp 
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/activepool/Del_activepool::${pool}_--prefix/request/$leader activepool_$stamp 
  #ETCDCTL_API=3 /TopStor/deltolocal.py activepool/$pool activepool
  pkill $pool
  crontab -l | grep -v Snap > /TopStordata/cronfile
  crontab -r 
  crontab /TopStordata/cronfile
  ETCDCTL_API=3 /pace/etcddel.py $leaderip balance $pool
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/balancedtype/Del_balance_${pool}/request balancedtype_$stamp 
  ETCDCTL_API=3 /pace/etcdput.py s$leaderip ync/balancedtype/Del_balance_${pool}/request/$leader balancedtype_$stamp 
  ETCDCTL_API=3 /pace/etcddel.py $leaderip vol $pool
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/all/request volumes_$stamp 
  ETCDCTL_API=3 /pace/etcdput.py $leaderip sync/volumes/all/request/$leader volumes_$stamp 

  echo > /etc/exports
   docker exec etcdclient /TopStor/logmsg.py DGsu5 info $userreq $pool
 fi 
fi
/pace/etcddel.py $leaderip requests/DGdestroypool/$myhost $myhost/$userreq
#systemctl restart zfs-zed
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish $userreq 
/pace/putzpool.py $leaderip
