#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/myip
leader=`echo $@ | awk '{print $1}'`
leaderip=`echo $@ | awk '{print $2}'`
myhost=`echo $@ | awk '{print $3}'`
hostip=`echo $@ | awk '{print $4}'`
realhost=`hostname`
echo $realhost | grep $myhost
if [ $? -ne 0 ];
then
 exit
fi
dev='enp0s8'
newip=`/TopStor/etcdget.py $leaderip ipaddr/$myhost`
oldip=`nmcli conn show mynode`

echo nmcli conn mod mynode ipv4.addresses $newip >/root/tmpmyip
nmcli conn mod mynode ipv4.addresses $newip 
echo $oldip | grep $newip
if [ $? -ne 0 ];
then
 echo running sleep >>/root/tmpmyip
 ./etcdput.py $leaderip rebootme/$myhost pls_fromIPADDR
# sleep 5
# /TopStor/resetdocker.sh
# reboot
fi
#/sbin/reboot
