#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
leader=`echo $@ | awk '{print $1}'`
leaderip=`echo $@ | awk '{print $2}'`
myhost=`echo $@ | awk '{print $3}'`
myip=`echo $@ | awk '{print $4}'`
hostname=$myhost
dev='enp0s8'1
gateway=`ETCDCTL_API=3 /TopStor/etcdget.py $leaderip gw/$leader`
gatewayn=`echo $gateway | wc -c`
oldgateway=`ip route | grep default | awk '{print $3}'`
oldgatewayn=`echo $oldgateway | wc -c`
if [ $gatewayn -le 3 ];
then
 if [ $oldgatewayn -le 6 ];
 then
  oldgateway=0 
 fi
else
 ./etcdput.py $myip gw/$hostname $gateway
 ./etcdput.py $leaderip gw/$hostname $gateway
 echo $leader | grep $myhost
 if [ $? -eq 0 ];
 then
   stamp=`date +%s`
  ./etcdput.py $leaderip sync/gateway/_____/request gateway_$stamp
   ./etcdput.py $leaderip sync/gateway/_____/request/$leader gateway_$stamp
 fi
#
 if [ $oldgatewayn -ge 7 ];
 then
  route del default gw $oldgateway 
 fi
 route add default gw $gateway
fi
