#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > ~/tmp
leader=`echo $@ | awk '{print $1}'`
leaderip=`echo $@ | awk '{print $2}'`
myhost=`echo $@ | awk '{print $3}'`
myip=`echo $@ | awk '{print $4}'`
dev='enp0s8'
hostname=$myhost
ntp=`ETCDCTL_API=3 ./etcdget.py $leaderip ntp/$leader`
ntpn=`echo $ntp | wc -c`
rm -rf /etc/chrony.conf
cp /TopStor/chrony.conf /etc/
if [ $ntpn -le 2 ];
then
 ntp='0.pool.ntp.org' 
fi
 ./etcdput.py $myip ntp/$hostname $ntp
 ./etcdput.py $leaderip ntp/$hostname $ntp
echo $leader | grep $myhost
 if [ $? -eq 0 ];
 then
   stamp=`date +%s`
  ./etcdput.py $leaderip sync/enteepe/_____/request enteepe_$stamp
   ./etcdput.py $leaderip sync/enteeepe/_____/request/$leader enteepe_$stamp
 fi

sed -i "s/MASTERSERVER/$ntp/g" /etc/chrony.conf
systemctl restart chronyd
