#!/usr/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/tmppartnerdel
cronthis='/TopStordata/cronthis.txt'
Partner=`echo $@ | awk '{print $1}'`;
issync=`echo $@ | awk '{print $2}'`;
userreq=`echo $@  | awk '{print $3}'`;
privilege="Replication";

contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
  leaderip=`docker exec -it etcdclient /TopStor/etcdgetlocal.py leaderip `
  leader=` docker exec -it etcdclient /TopStor/etcdgetlocal.py leader `
  myhost=`docker exec -it etcdclient /TopStor/etcdgetlocal.py clusternode`
  myhostip=`docker exec -it etcdclient /TopStor/etcdgetlocal.py clusternodeip`
  echo $myhost | grep $leader
  if [ $? -eq 0 ];
  then
	etcdip=$leaderip
  else
	etcdip=$myhostip
  fi
  echo hihihi
  docker exec -it etcdclient /TopStor/logmsg.py Partner1003 info $userreq $Partner
  echo 222222 $etcdip $Partner $Partner
  echo /TopStor/etcddel.py $etcdip Partner $Partner
  hi=`/TopStor/etcddel.py $etcdip Partner $Partner`
  echo 3333333
  /TopStor/etcddel.py $etcdip repli $Partner
  echo 4444444
  crontab -l | grep -v $Partner > $cronthis
  crontab $cronthis
  echo $issync | grep yes 
  if [ $? -ne 0 ];
  then
    stamp=`date +%s`;
    ./etcdput.py $leaderip sync/replipart/PartnerDel_${Partner}_yes_${userreq}_/request  replipart_$stamp
    ./etcdput.py $leaderip sync/replipart/PartnerDel_${Partner}_yes_${userreq}_/request/$myhost  replipart_$stamp
  fi
  docker exec -it etcdclient /TopStor/logmsg.py Partner1004 info $userreq $Partner
fi
