#!/bin/sh
export ETCDCTL_API=3
cd /TopStor/
echo $@ > /root/rebootme
echo $@ > /TopStordata/rebootstatus
web='/var/www/html/des20/Data/HostManualconfigstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
runningpools='/pacedata/pools/runningpools';
glog='/var/www/html/des20/Data/TopStor.log';
txtres='/TopStordata/'`basename $0`'.txt'
myhost=`hostname -s`
rm -rf $txtres &>/dev/null
#hostip=`echo $@ | awk '{ print $1 }'`;
#subnet=` echo $@ | awk '{ print $3 }'`;
#oldip=`pcs resource show CC | grep Attribute | awk -F'ip=' '{print $2}' | awk '{print $1 }'`
#oldsubnet=` echo $@ | awk '{ print $4 }'`;
echo wait
echo hi > /root/HostCC2
echo shuttingdown 1 >> /root/HostCC2
echo shuttingdown 1 
mkdir /tmp/cpools 2>/dev/null
rm -rf /tmp/cpools/*
docker stop $(docker ps -aq)
targetcli iscsi/ ls | grep ${myhost}
if [ $? -eq 0 ];
then
 targetcli iscsi/ delete iqn.2016-03.com.${myhost}:data
fi
echo shuttingdown 2 >> /root/HostCC2
echo shuttingdown 2
#/pace/keysend.sh $hostip
/sbin/rabbitmqctl stop_app
echo shuttingdown 3 >> /root/HostCC2
echo shuttingdown 3
/sbin/iscsiadm --mode node --logoutall=all
echo shuttingdown 4 >> /root/HostCC2
echo shuttingdown 4 
echo shuttingdown 6 >> /root/HostCC2
whyreboot=`echo $@ | awk '{ print $1 }'`;
echo $whyreboot | grep ipchange
if [ $? -eq 0 ];
then
 echo shuttingdown 7 >> /root/HostCC2
 oldip=`echo $@ | awk '{ print $2 }'`;
 oldipsubnet=`echo $@ | awk '{ print $3 }'`;
 newips=`echo $@ | awk '{ print $4 }'`;
 newipsubnet=`echo $@ | awk '{ print $5 }'`;
# /TopStor/HostManualconfigCC $@
 echo shuttingdown 8 >> /root/HostCC2
 targetcli iscsi/iqn.2016-03.com.$myhost:t1/tpg1/portals delete 0.0.0.0 3260
 targetcli iscsi/iqn.2016-03.com.$myhost:t1/tpg1/portals delete $oldip 3266
 targetcli iscsi/iqn.2016-03.com.$myhost:t1/tpg1/portals create $newips 3266
 targetcli saveconfig /pacedata/targetconfig
 echo shuttingdown 9 >> /root/HostCC2
fi
echo $whyreboot | grep QS 
if [ $? -eq 0 ];
then
 echo shuttingdown 7_QS >> /root/HostCC2
 cd /TopStor
 git checkout $whyreboot
 cd /pace
 git checkout $whyreboot
 cd /var/www/html/des20/
 git checkout $whyreboot
 echo shuttingdown 8_QS >> /root/HostCC2
fi
echo $whyreboot | grep reset 
if [ $? -eq 0 ];
then
 users=`cat /etc/passwd | grep TopStor | grep -v Everyone | awk -F':' '{print $1}'`
 systemctl stop etcd
 rm -rf /var/lib/etcd/member/*
fi
pkill httpd
echo shuttingdown 10 >> /root/HostCC2
sync
sync
sync
/sbin/zpool export -a &
echo shuttingdown 11 >> /root/HostCC2
#pkill zfsping
echo finish > /TopStordata/rebootstatus
/sbin/reboot
