#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/tmpperioddel
leaderip=` echo $@ | awk '{print $1}'`;
periodel=` echo $@ | awk '{print $2}'`;
userreq=` echo $@ | awk '{print $3}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
	rm $txtres 2>/dev/null
privilege="SnapShots";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi
  docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq 
  docker exec etcdclient /TopStor/logmsg.py Snap1043 info $userreq $periodel
 /bin/crontab -l | grep -v "$periodel"
 if [ $? -eq  0  ]; then
   #was if -ne docker exec etcdclient /TopStor/logmsg.py Snap1044 error $userreq $periodel
 /bin/crontab -l | grep -v "$periodel" > /TopStordata/thiscron
 /bin/crontab /TopStordata/thiscron
 /pace/etcddel.py $leaderip Snapperiod $periodel 
 /pace/etcddel.py $leaderip call $periodel 
 stamp=`date +%s`;
 /pace/etcdput.py $leaderip sync/Snapperiod/Del_$periodel/request/$myhost Snapperiod_$stamp
 /pace/etcdput.py $leaderip sync/Snapperiod/Del_$periodel/request Snapperiod_$stamp
# ETCDCTL_API=3 /TopStor/broadcast.py  PeriodManage /TopStor/etctocronlocal.sh 
 docker exec etcdclient /TopStor/logmsg.py Snap1045 info $userreq $periodel
fi;
/pace/putzpool.py $leaderip & 
fi
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
