#!/usr/bin/sh
echo $@> /root/snapshotonce
export ETCDCTL_API=3
cd /TopStor/
leaderip=`echo $@ | awk '{print $1}'`;
name=`echo $@ | awk '{print $2}'`;
pDG=`echo $@ | awk '{print $3}'`;
FileS=` echo $@ | awk '{print $4}'`;
receiver=` echo $@ | awk '{print $5}'`;
userreq=` echo $@ | awk '{print $NF}'`;
docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq 
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
echo $receiver | grep $name
if [ $? -ne 0 ];
then 
 privilege="Replication";
else
 privilege="SnapShots";
fi
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
/TopStor/SnapshotnowOnce $leaderip $name $pDG $FileS $receiver $userreq > $txtres
fi
docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
/pace/putzpool.py
