#!/bin/sh
export ETCDCTL_API=3
echo $@ >/root/tmp
cd /TopStor
stamp=`date +%s`;
cronout='/TopStordata/cronoutput.log';
oper=$@; 
echo oper=$oper > $cronout
leaderip=`echo $@ | awk -F/ '{print $1}'`;
hostnam=`echo $@ | awk -F/ '{print $2}'`;
oper1=`echo $oper | awk '{print $3}'`;
receiver=`echo $oper | awk '{print $NF}'`;
#realoper=`echo $oper1 | awk -F'/' '{print $2"/"$3}'`;
realoper=$oper1
oper2=`echo $oper | awk '{print $4}'`;
txtres='/TopStordata/'`basename $0`$userreq'.txt'
rm $txtres 2>/dev/null
echo oper1=$oper1 >> $cronout;
echo oper2=$oper2 >> $cronout;
echo stamp=$stamp >> $cronout
keep=`echo $oper2 | awk -F. '{print $2}'`;
snaptype=`echo $oper2 | awk -F. '{print $1}'`;
echo keep=$keep >> $cronout
declare currentsnaps=`/sbin/zfs list -t snapshot | grep -w "$realoper" | grep -w "$oper2" | awk '{print $1}'`;
echo currentsnaps=$currentsnaps >> $cronout
oldsnap=`echo "${currentsnaps[@]}" | sort | head -n 1` ;
echo oldsnap=$oldsnap >> $cronout
count=0
countsnap=`echo  "$currentsnaps" | wc -l `;
echo countsnap=$countsnap >> $cronout 
countsnap=$(($countsnap+1));
echo countsnapplus=$countsnap >> $cronout
keep=$(($keep+0));
echo keeppluszero=$keep >> $cronout
timenow=`date`;
userreq='system';
replicationflag='hi'
isreceiver='hi'
if (( $countsnap >  $keep )); then 
 replicationflag=$oldsnap 
 isreceiver=$receiver
 echo $isreceiver | grep NoReceive
 if [ $? -eq  0 ];
 then
  docker exec etcdclient /TopStor/logmsg.py Snap1022 info $userreq $oldsnap
  echo /sbin/zfs destroy $oldsnap > /root/tmpcron
  /sbin/zfs destroy $oldsnap > /root/tmpcron
  if [ $? -ne  0  ]; then
   docker exec etcdclient /TopStor/logmsg.py Snap1023 error $userreq $oldsnap
  else
   docker exec etcdclient /TopStor/logmsg.py Snap1025 info $userreq $oldsnap
  fi
 fi
fi
echo hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
echo repli_${replicationflag}repli_
newsnap2=`echo $oper2.$stamp`;
echo newsnap2=$newsnap2 >> $cronout
newsnap=`echo $oper1@$newsnap2`;
echo newsnap=$newsnap >> $cronout
 docker exec etcdclient /TopStor/logmsg.py Snap1026 info $userreq $newsnap
/sbin/zfs snapshot $newsnap &> ${txtres}$stamp
echo snapshotresult : >> $cronout
cat ${txtres}$stamp >> $cronout 
echo filenameis=${txtres}$stamp >> $cronout
err=`wc -c  ${txtres}$stamp | awk '{print $1}'`;
if [[ $err -ge  4  ]]; then 
   docker exec etcdclient /TopStor/logmsg.py Snap1028 error $userreq $newsnap
   echo _newsnapError_newsnap
else 
   /sbin/zfs set snap:type=$snaptype $newsnap
   docker exec etcdclient /TopStor/logmsg.py Snap1030 info $userreq $newsnap
   echo _newsnap${newsnap}_newsnap
fi
