#!/bin/sh
echo $@ > /root/snapnowparam
cd /TopStor
leaderip=`echo $@ | awk '{print $1}'`;
name=`echo $@ | awk '{print $2}'` ;
pool=`echo $@ | awk '{print $3}'`;
vol=`echo $@ | awk '{print $4}'`;
receiver=`echo $@ | awk '{print $5}'` ;
userreq=`echo $@ | awk '{print $6}'` ;
stamp=`date +%s`;
snapshot=$pool'/'$vol'@'${name}'.'$stamp
echo new snpashot-$snapshot
shortreceiver=`echo $receiver | awk -F'_' '{print $1}'`
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi

docker exec etcdclient /TopStor/logqueue.py `basename "$0"` start system 
echo $receiver | grep NoReceiver
if [ $? -ne 0 ];
then 
 docker exec etcdclient /TopStor/logmsg.py Replispacest01 info $userreq $vol $shortreceiver  
 echo /TopStor/logmsg.py Replispacest01 info $userreq $vol $shortreceiver  
else
 docker exec etcdclient /TopStor/logmsg.py Snap1026 info $userreq $name 
fi
zfs snapshot $snapshot 
if [ $? -ne 0  ]; then
      echo failed
      docker exec etcdclient /TopStor/logmsg.py Snap1028 error $userreq $name 
      exit 1;
else
 docker exec etcdclient /TopStor/logmsg.py Snap1030 info $userreq $name 
fi 
result='init'
zfs set snap:type=Once $snapshot 
echo $receiver | grep NoReceive
if [ $? -eq 0 ];
then
	waiting=0
else
 	waiting=1
fi
while [ $waiting -eq 1 ];
do
  running=`/TopStor/etcdget.py $etcd running/$receiver`
  echo $running | grep $receiver
  if [ $? -eq 0 ];
  then
   echo waiting the current replications to finish
   queue=`ps -ef | grep Snapshotnow | wc -l`
   if [ $queue -le 10 ];
   then
    /TopStor/etcdput.py $leaderip running/$receiver no
    exit
    waiting=0
   fi
   sleep 1
  else
   waiting=0
  fi
done
echo $receiver | grep NoReceive
if [ $? -ne 0 ];
then
 zfs set partner:receiver=$receiver $snapshot 
 /TopStor/etcdput.py $leaderip running/$receiver $receiver
 /TopStor/etcdput.py $leaderip sync/running/____/request running_$stamp
 /TopStor/etcdput.py $leaderip sync/running/____/request/$leader running_$stamp
 echo ./replicatenow.py $leaderip $etcd $snapshot $receiver
 result=`./replicatenow.py $leaderip $etcd $snapshot $receiver`
 result=`echo $result | grep 'result_' | awk -F'result_' '{print $2}'`
 echo .................................................................
 echo result=$result
 echo ............................................
 echo $result | grep 'fail'
 if [ $? -eq 0 ];
 then
  #./logmsg.py Replispacefa01 error $userreq $shortreceiver $vol
  docker exec etcdclient /TopStor/logmsg.py Streamfa01 error $userreq $vol $shortreceiver
 else
  docker exec etcdclient /TopStor/logmsg.py Replispacesu01 info $userreq $vol $shortreceiver
 fi 
 /TopStor/etcdput.py $leaderip running/$receiver finish 
 /TopStor/etcdput.py $leaderip sync/running/____/request running_$stamp
 /TopStor/etcdput.py $leaderip sync/running/____/request/$leader running_$stamp
fi 
docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop system 
#sleep 2;
