#!/usr/bin/bash
source /root/.bash_profile
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/Snapshotnowhost
pDG=`echo $@ | awk '{print $1}'`;
DG=`echo $@ | awk -F/ '{print $1}'`;
vol=`echo $@ | awk '{print $1}'| awk -F/ '{print $2}'`;
stype=`echo $@ | awk '{print $2}' | awk -F'.' '{print $1}'`;
receiver=` echo $@ | awk '{print $NF'}`
shortreceiver=`echo $receiver | awk -F'_' '{print $1}'`
echo $pDG
pp=`/sbin/zpool list | grep $DG`
echo pp=$pp
echo $pp | grep $DG
if [ $? -ne 0 ]; 
then
 echo host not owner
 exit
fi

leaderip=` docker exec etcdclient /TopStor/etcdgetlocal.py leaderip`
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi

docker exec etcdclient /TopStor/logqueue.py `basename "$0"` start system 

userreq='system'
stamp=`date +%s`
pp=`/sbin/zpool list | grep $DG`
echo pp=$pp
echo $pp | grep $DG
if [ $? -ne 0 ]; 
then
 echo host not owner
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish system 
 exit
else
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running system 
fi
echo $receiver | grep NoReceiver
if [ $? -ne 0 ];
then 
 docker exec etcdclient /TopStor/logmsg.py Replispacest01 info $userreq $vol $shortreceiver  
 echo /logmsg.py Replispacest01 info $userreq $vol $shortreceiver  
fi
result=`/TopStor/Snapshotnow $leaderip $myhost $@`
res=`echo $result | awk -F'_newsnap' '{print $2}'`
soldsnap=`echo $result | awk -F'repli_' '{print $2}'`
echo $res | grep Erro
if [ $? -eq 0 ];
then
 exit
fi
snapshot=$res 
echo thesnaps: $snapshot , $stype
zfs set snap:type=$stype $snapshot 
echo $receiver | grep NoReceiver 
if [ $? -ne 0 ];
then 
 echo $receiver | grep NoReceive
 if [ $? -eq 0 ];
 then
 	waiting=0
 else
 	waiting=
 fi
 echo $receiver, $waiting
 waiting=0
 while [ $waiting -eq 1 ];
 do 
  running=`/TopStor/etcdget.py $leaderip running $receiver`
  echo 'checking'$running | grep $receiver 
  if [ $? -eq 0 ];
  then
   echo waiting the current replications to finish in Snapshotnowhost
   queue=`ps -ef | grep Snapshotnow | wc -l`
   if [ $queue -ge 10 ];
   then
    stamp=`date +%s`
    /TopStor/etcddel.py $leaderip running $receiver
    #./etcdput.py $leaderip running/stub/$receiver  no
    #./etcdput.py $leaderip sync/running/____/request running_$stamp
    #./etcdput.py $leaderip sync/running/____/request/$leader running_$stamp
    exit
    waiting=0
   fi
   sleep 1
  else
   waiting=0
  fi
 done
 echo $receiver | grep NoReceive
 if [ $? -ne 0 ];
 then
  #./etcdput.py $leaderip running/$myhost/$receiver $receiver 
  #./etcdput.py $leaderip sync/running/____/request running_$stamp
  #./etcdput.py $leaderip sync/running/____/request/$leader running_$stamp
  zfs set partner:receiver=$receiver $snapshot
  echo /TopStor/replicatenow.py $leaderip $etcd $snapshot $receiver >/root/snapshotpls
  echo /TopStor/replicatenow.py $leaderip $etcd $snapshot $receiver 
  #result=`/TopStor/replicatenow.py $leaderip $etcd $snapshot $receiver 2>/root/replicatenow`
  /TopStor/replicatenow.py $leaderip $etcd $snapshot $receiver >/TopStordata/remotereplicatenow 2>/root/replicatenow
  result=`cat /TopStordata/remotereplicatenow`
  echo result=$result > /root/snaph 
  echo result=$result 
  
  result=`echo $result | grep 'replicatenow_' | awk -F'replicatenow_' '{print $2}'`
  echo .................................................................
  echo result=$result
  echo ............................................
  echo 'hi'$result | grep 'success'
  if [ $? -ne 0 ];
  then
   #./logmsg.py Replispacefa01 error $userreq $shortreceiver $vol
   echo removing new snap $snapshot from the source
   echo /sbin/zfs destroy $snapshot
   /sbin/zfs destroy $snapshot
   if [ $? -ne  0  ]; then
    docker exec etcdclient /TopStor/logmsg.py Snap1023 error $userreq $snapshot
   else
    docker exec etcdclient /TopStor/logmsg.py Snap1025 info $userreq $snapshot
   fi
   docker exec etcdclient /TopStor/logmsg.py Streamfa01 error $userreq $vol $shortreceiver
  else
   echo removing oldsnap $soldsnap from the source
   echo /sbin/zfs destroy $soldsnap
   /sbin/zfs destroy $soldsnap
   if [ $? -ne  0  ]; then
    docker exec etcdclient /TopStor/logmsg.py Snap1023 error $userreq $soldsnap
   else
    docker exec etcdclient /TopStor/logmsg.py Snap1025 info $userreq $soldsnap
   fi
    echo successfulwork
    docker exec etcdclient /TopStor/logmsg.py Replispacesu02 info $userreq $vol $shortreceiver
  fi 
  docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish system 
 fi
 #./etcdput.py $leaderip running/$myhost/$receiver finished 
 #./etcdput.py $leaderip sync/running/____/request running_$stamp
 #./etcdput.py $leaderip sync/running/____/request/$leader running_$stamp
fi
docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish system 
