#!/bin/sh

leaderip=`echo $@ | awk '{print $1}'`
volume=`echo $@ | awk '{print $2}'`
pool=`echo $@ | awk '{print $3}'`

volusers=$(awk 'BEGIN { found=0 } /^rpc:/ { found=1; next } found { print $1, $3 }' $pool'/user_'$volume | cut -d: -f1,3)
userstring="/"
while read -r username id; do
	if [[ $username != $rootname ]];
	then
  		userstring+="${username}:${id}/"
	fi
done <<< "$volusers"
/TopStor/etcdput.py $leaderip tenant/$volume/users $userstring

