#!/bin/bash
echo $@ > /root/unixdeluser
export ETCDCTL_API=3
cd /TopStor
userreq=`echo $@  | awk '{print $1}'`;
pool=`echo $@  | awk '{print $2}'`;
volume=`echo $@  | awk '{print $3}'`;
username=`echo $@ | awk '{print $4}'`;
docker exec etcdclient /TopStor/logmsg.py Tenantst02 info $userreq $username $volume 
docker ps | grep $volume
if [ $? -ne 0 ];
then
	docker exec etcdclient /TopStor/logmsg.py Tenantfa02 error $userreq $username $volume 
	exit
fi
sed -i "/$username/d" $pool'/user_'$volume
docker exec $container cat /etc/passwd | grep $username
if [ $? -eq 0 ];
then	
	docker exec etcdclient /TopStor/logmsg.py Tenantsu02 info $userreq $username $volume 
else
	docker exec etcdclient /TopStor/logmsg.py Tenantfa02 error $userreq $username $volume 
fi
/TopStor/TenantUserList $leaderip $volume $pool
