#!/bin/bash
echo $@ > /root/unixchangeuser
export ETCDCTL_API=3
cd /TopStor

leaderip=`echo $@  | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
grps=`echo $@  | awk '{print $3}' | awk -F'groups' '{print $2}'`;
pool=`echo $@  | awk '{print $4}'`;
volume=`echo $@  | awk '{print $5}'`;
userreq=`echo $@  | awk '{print $6}'`;

volip=`cat /$pool/exports.$volume | grep SUMMARY | awk -F'/' '{print $14'}`
resname='NFS-'$volip
cat /$pool/exports.$volume | grep $username
if [ $? -eq 0 ];
then
 
	docker exec etcdclient /TopStor/logmsg.py Tenantst04 error $userreq $username $volume
	exit
fi
docker exec etcdclient /TopStor/logmsg.py Tenantst03 info $userreq $username $volume 
sed -i "s/,$username//g" /$pool'/group_'$volume
sed -i "s/:$username/:/g" /$pool'/group_'$volume
echo group$grps | grep 'NoGroup'
if [ $? -ne 0 ];
then
	sed -i "/^${grps}:/s/$/,${username}/" /$pool'/group_'$volume
fi

sed -i "s/:,/:/g" /$pool'/group_'$volume

docker restart $resname
docker exec etcdclient /TopStor/logmsg.py Tenantsu03 info $userreq $username $volume 
/TopStor/TenantUserList $leaderip $volume $pool
