#!/bin/bash
echo $@ > /root/unixadduser
export ETCDCTL_API=3
cd /TopStor
userreq=`echo $@  | awk '{print $1}'`;
pool=`echo $@  | awk '{print $2}'`;
volume=`echo $@  | awk '{print $3}'`;
username=`echo $@ | awk '{print $4}'`;
userid=`echo $@ | awk '{print $5}'`;
docker exec etcdclient /TopStor/logmsg.py Tenantst01 info $userreq $username $volume 
docker ps | grep $volume
if [ $? -ne 0 ];
then
	docker exec etcdclient /TopStor/logmsg.py Tenantfa01 error $userreq $username $volume 
	exit
fi
echo "$rootname:x:$rootid:$rootid:$rootname:/NoHome:/sbin/nologin" >> $pool'/user_'$volume
#docker exec $container adduser $username -H -D -s /sbin/nologin -u $userid
docker exec $container cat /etc/passwd | grep $username
if [ $? -eq 0 ];
then	
	docker exec etcdclient /TopStor/logmsg.py Tenantsu01 info $userreq $username $volume 
else
	docker exec etcdclient /TopStor/logmsg.py Tenantfa01 error $userreq $username $volume 
fi
