#!/bin/sh
cd /TopStor
echo $@ > /root/usersync
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
leader=`echo $@ | awk '{print $1}'`;
leaderip=`echo $@ | awk '{print $2}'`;
myhost=`echo $@ | awk '{print $3}'`;
myip=`echo $@ | awk '{print $4}'`;
username=`echo $@ | awk '{print $5}'`;
userpass=`echo $@ | awk '{print $6}'`;
userid=`echo $@ | awk '{print $7}'`;
usergd=`echo $@ | awk '{print $8}'`;
userhome=`echo $@ | awk '{print $9}'`;
userreq='system';
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
cat /etc/passwd | grep $username
if [ $? -eq 0 ];
then
 #/TopStor/logmsg.py Unlin10211 warning $userreq $username
 /TopStor/UnixDelUserlocal_sync $myhost $username system
fi
#/TopStor/logmsg.py Unlin10188 info $userreq $username
pas=`/TopStor/decthis.sh $username $userpass | awk -F'_result' '{print $2}'`
groupdel $username
groupadd -g $usergd $username
rm -rf /home/$username 2>/dev/null
echo $userhome | grep NoHome
if [ $? -eq 0 ];
then
 homebase='-b /NoHome -M'
else
 userhome=`echo $userhome | awk -F'/' '{print $2}'`
 homebase='-b /'$userhome' -M'  
fi
cp /TopStor/smbuserfix.sh /etc/
useradd -c"TopStor"$userpass $homebase -g $usergd -u $userid -p $userpass -s /usr/sbin/nologin $username
echo useradd \-c"TopStor"$userpass $homebase \-g $usergd \-u $userid \-p $userpass \-s /usr/sbin/nologin $username
currentcifs=`docker ps | awk '{print $NF}' | grep CIFS | grep -v 'CIFS_'`
echo "$currentcifs" | while read y
do 
 echo $y | grep CIFS
 if [ $? -eq 0 ];
 then
 	echo dock=$y
 	echo docker exec $y  sh /hostetc/smbuserfix.sh x $username $pas 
 	docker exec $y  sh /hostetc/smbuserfix.sh x $username $pas 
 fi
done 
#(echo $userpass; echo $userpass) | /usr/bin/smbpasswd -s -a $username 2>> $txtres
#cat $txtres
 #echo $userpass > key/${username}fixed
 #gpg -u "QuickStor" -r"QuickStor" key/${username}fixed
 #chmod 400 key/${username}fixed.gpg;
 #rm -rf key/${username}fixed
 #/pace/etcdsync.py $myip usersinfo/$username usersinfo/$username 
 #/pace/etcdsync.py $myip usershash/$username usershash/$username 
 #/TopStor/logmsg.py Unlin10222 info $userreq $username
fi
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
	echo hi2
	stamp=`date +%s%N`
	myscript=`basename "$0"`
	params=`echo $myscript $@ $stamp | sed 's\ \\_\g'`
	/pace/etcddel.py $leaderip sync/user _${username}_
	/pace/etcdput.py $leaderip sync/user/$params/request/$myhost user_${username}_$stamp
	/pace/etcdput.py $leaderip sync/user/$params/request user_${username}_$stamp
fi

cd /pace
