#!/bin/sh
cd /TopStor
export ETCDCTL_API=3 
echo $@ > /root/groupsync
web='/var/www/html/des20/Data/Usersstatus.log';
logging='/var/www/html/des20/Data/currentinfo2.log';
txtres='/TopStordata/'`basename $0`'.txt'
rm -rf $txtres &>/dev/null
glog='/var/www/html/des20/Data/TopStor.log';
leader=`echo $@ | awk '{print $1}'`;
leaderip=`echo $@ | awk '{print $2}'`;
myhost=`echo $@ | awk '{print $3}'`;
myip=`echo $@ | awk '{print $4}'`;
username=`echo $@ | awk '{print $5}'`;
userid=`echo $@ | awk '{print $6}'`;
usergd=`echo $@ | awk '{print $7}'`;
groupusers=`echo $@ | awk '{print $8}'`;
userpass='df323jdlda'$RANDOM
pas=`/TopStor/encthis.sh $username $userpass | awk -F'_result' '{print $2}'`
userreq='system';
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
cat /etc/group | grep $username
if [ $? -eq 0 ];
then
 #/TopStor/logmsg.py Unlin11211 warning $userreq $username
 /TopStor/UnixDelGrouplocal $myhost $username system
fi
#/TopStor/logmsg.py Unlin11188 info $userreq $username
groupdel $username
groupadd -g $usergd $username
homebase='-b /NoHome -M'
echo useradd -c"TopStorGroup"$userpass $homebase -g $usergd -u $userid -p $userpass -s /usr/sbin/nologin $username
useradd -c"TopStorGroup"$userpass $homebase -g $usergd -u $userid -p $userpass -s /usr/sbin/nologin $username
#/TopStor/UnixChangeGroup_sync $username $groupusers $userreq
#/pace/etcdsync.py $myip usersigroup/$username usersigroup/$username 
#/TopStor/logmsg.py Unlin11222 info $userreq $username
fi
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
	echo hi2
	stamp=`date +%s%N`
	myscript=`basename "$0"`
	params=`echo $myscript $@ $stamp | sed 's\ \\_\g'`
	/pace/etcddel.py $leaderip sync/user _${username}_
	/pace/etcdput.py $leaderip sync/user/$params/request/$myhost user_${username}_$stamp
	/pace/etcdput.py $leaderip sync/user/$params/request user_${username}_$stamp
fi

cd /pace
