#!/bin/sh
echo $@ > /root/usrchapass
export ETCDCTL_API=3

cd /TopStor
username=`echo $@ | awk '{print $1}'`;
pas=`docker exec etcdclient /TopStor/etcdgetlocal.py usershash/$username` 
userpass=`/TopStor/decthis.sh $username $pas | awk -F'_result' '{print $2}'`
userreq=`echo $@  | awk '{print $2}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
	leaderip=`docker exec etcdclient /TopStor/etcdgetlocal.py leaderip`
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 
	fi
	usermod  -p $userpass $username
 	docker exec etcdclient /TopStor/etcdputlocal.py $myip 'usershash/'$username $pas 2>/dev/null
	echo $username | grep -w admin
	if [ $? -eq 0 ];
	then
 		usermod $username -c"AdminStor"$pas
		echo $etcd | grep $leaderip
		if [ $? -eq 0 ];
		then
			/TopStor/promserver.sh $leaderip
		fi
	else
 		usermod $username -c"TopStor"$pas
		currentcifs=`docker ps | egrep 'CIFS|HOM' | awk '{print $1}'`
		if [[ ! -z $currentcifs ]]
		then
 			echo "$currentcifs" | while read y; do docker exec $y  sh /hostetc/smbuserfix.sh x $username $userpass;  done; 
		fi
 
	fi
	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish $userreq
fi
