#!/bin/sh
cd /TopStor
echo $@ > /root/groupdel
export ETCDCTL_API=3
leaderip=`echo $@  | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
echo $username | grep -w Everyone
if [ $? -eq 0 ];
then
exit
fi
userreq=`echo $@ | awk '{print $3}'`;
pullsync=`echo $@ | awk '{print $4}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;

if [[ $contrun == 'true' ]]
then

	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq 
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo s$pullsync | grep pull
	if [ $? -ne 0 ];
	then
  		docker exec etcdclient /TopStor/logmsg.py Unlin1104 info $userreq $username
	fi
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
	fi

userdel -f  $username 
rm  key/${username}fixed
sleep 2
cat /etc/passwd |  grep $username
if [ $? -eq 0 ]; then
	echo s$pullsync | grep pull
	if [ $? -ne 0 ];
	then
  		docker exec etcdclient /TopStor/logmsg.py Unlin1g1001 error $userreq $myhost
	fi
else
  #/TopStor/broadcast.py GroupDel /TopStor/pump.sh UnixDelGroup_sync -d$myhost $username $userreq
 echo usename=$username
 groupdel $username 
 ETCDCTL_API=3 /pace/etcdget.py $etcd usersigroup $username 
 pool=`ETCDCTL_API=3 /pace/etcdget.py $etcd usersigroup/$username | awk -F'/' '{print $2}'`
 echo Home=$pool
 echo $pool | grep pdhcp
 if [ $? -eq 0 ];
 then
 vol=`ETCDCTL_API=3 /pace/etcdget.py $etcd usersigroup/$username | awk -F'/' '{print $3}'`
 echo vol=$vol $userreq
# ./VolumeDeleteHome.py $pool $vol $userreq
 fi
 /pace/etcddel.py $etcd usersigroup $username
 echo s$pullsync | grep pull
 if [ $? -ne 0 ];
 then
	 docker exec etcdclient /TopStor/logmsg.py Unlin1110 info $userreq $username
 fi
fi;
fi

echo $leader | grep $myhost
if [ $? -eq 0 ];
then
	stamp=`date +%s%N`
	myscript=`basename "$0"`
	params=`echo $myscript $@ $stamp | sed 's\ \\_\g'`
	/pace/etcdput.py $etcd sync/group/$params/request/$myhost group_${username}_$stamp
	/pace/etcdput.py $etcd sync/group/$params/request group_${username}_$stamp
fi
docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
