#!/bin/sh
echo $@ > /root/unixadduser
export ETCDCTL_API=3
cd /TopStor
leaderip=`echo $@  | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
homePool=`echo $@ | awk '{print $3}'`;
usergroups=`echo $@ | awk  '{print $4}'`;
grps=`echo $grpusers | sed 's/groups//g' | sed 's/\,/ /g'`
userpass=`echo $@ | awk '{print $5}'`;
size=`echo $@ | awk '{print $6}'`;
HomeAddr=`echo $@  | awk '{print $7}' `;
HomeSubnet=`echo $@  | awk '{print $8}'`;
host=`echo $@ | awk '{print $9}'`;
userreq=`echo $@  | awk '{print $10}'`;
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 
 		/pace/etcdget.py $etcd volumes --prefix | grep -w $username
	 	if [ $? -eq 0 ];
 		then
 			docker exec etcdclient /TopStor/logmsg.py Unlin1021uv warning $userreq $username
  			docker exec etcdclient/TopStor/logqueue.py `basename "$0"` stop $userreq 
  			exit
 		fi
 		./etcdget.py $etcd user --prefix | grep -w $username 
 		if [ $? -eq 0 ];
 		then
 	echo hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
  			docker exec etcdclient /TopStor/logmsg.py Unlin1021uu warning $userreq $username
  			docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
  			exit
 		fi
	fi
 docker exec etcdclient /TopStor/logmsg.py Unlin1018 info $userreq $username
 userdel -f  $username
 #pas=`echo $userpass | openssl enc -e -base64 -aes-256-ctr -nopad -nosalt -k '#skMe22'$username`
 pas=`/TopStor/encthis.sh $username $userpass | awk -F'_result' '{print $2}'` 
 homebase='-b /NoHome -M'
 groupdel $username
 useradd -c"TopStor"$pas $homebase -p $userpass -s /usr/sbin/nologin $username 
 echo $homePool | grep 'NoHome'
 if [ $? -ne 0 ];
 then
  docker exec etcdclient docker exec etcdclient /TopStor/logmsg.py Unlin1024 info  $userreq $username $homedir
  homedir=$homePool
  homebase='-b /'$homedir' -M'  
  echo hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
  echo /TopStor/VolumeCreateHOME $leaderip $homePool $username $size $username $HomeAddr $HomeSubnet active $userreq $myhost $userreq 
  /TopStor/VolumeCreateHOME $leaderip $homePool $username $size $username $HomeAddr $HomeSubnet active $userreq $myhost $userreq 
  echo hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
  #usermod -d $homdedir/$usrename $username
  # it is in the VolCreate HOME chmod o-rwx /$homedir/$username -R
 else
  docker exec etcdclient /TopStor/logmsg.py Unlin1023 warning $userreq $username
 fi
echo useradd \-c"TopStor"$pas $homebase \-p $userpass \-s /usr/sbin/nologin $username
 currentcifs=`docker ps | egrep 'CIFS|HOM' | awk '{print $1}'`
 echo "$currentcifs" | while read y; do docker exec $y  sh /hostetc/smbuserfix.sh x $username $userpass;  done; 
 #/bin/smbpasswd -x $username
 docker exec intsmb /root/smbuser.sh $username $userpass
 #docker exec etcdsmb "( echo $userpass; echo $userpass) | /bin/smbpasswd -s -a $username"

 #mkdir -p /Data/Common/$username;
 #chown $username /Data/Common/$username;
 userline=`cat /etc/passwd | grep $username`
 if [ $? -ne  0  ]; then
  docker exec etcdclient /TopStor/logmsg.py Unlin1020 error $userreq $username
 else 
 # openssl rsautl -encrypt -inkey key/public_key.pem -pubin -in <( echo $userpass) -out key/$username;  
  userid=`echo $userline | awk -F':' '{print $3}'`
  usergd=`echo $userline | awk -F':' '{print $4}'`
  userhome=`echo $userline | awk -F':' '{print $6}'`
  #userhash=`echo $userline | awk -F':' '{print $5}' | awk -F'TopStor' '{print $2}'`
  userhash=$pas
  
  /TopStor/etcdput.py $etcd 'usersinfo/'$username $userid':'$usergd':/'$homePool'/'$username'/'$size'/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no/no'
  /TopStor/etcdput.py $etcd 'usershash/'$username $userhash
  #/TopStor/broadcast.py UserAdd /TopStor/pump.sh UnixAddUser_sync -d$myhost $username $userhash $userid $usergd $userhome
 echo $etcd 2222222222222222222222222222222222222222222222222222222222222222 
  /TopStor/UnixChangeUser $leaderip $username $usergroups $userreq create
 echo $etcd 2222222222222222222222222222222222222222222222222222222222222222 
  docker exec etcdclient /TopStor/logmsg.py Unlin1022 info $userreq $username
 fi 
fi
#echo ln -f /etc/passwd  /opt/passwds/passwd
#ln -f /etc/passwd  /opt/passwds/passwd
#ln -f /etc/group  /opt/passwds/group
#ln -f /etc/shadow  /opt/passwds/shadow
echo hi1
echo $leader | grep $myhost
if [ $? -eq 0 ];
then
	echo hi2
	stamp=`date +%s%N`
	myscript=`basename "$0"`
	params=`echo $myscript $@ $stamp | sed 's\ \\_\g'`
	/pace/etcddel.py $leaderip sync/user _${username}_
	/pace/etcdput.py $leaderip sync/user/$params/request/$myhost user_${username}_$stamp
	/pace/etcdput.py $leaderip sync/user/$params/request user_${username}_$stamp
fi
echo hi3
docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish $userreq 
