#!/bin/sh
echo $@ > /root/delusersync
export ETCDCTL_API=3
cd /TopStor
web="/var/www/html/des20/Data/Usersstatus.log";
logging="/var/www/html/des20/Data/currentinfo2.log";
myhost=`hostname -s`
glog='/var/www/html/des20/Data/TopStor.log'
username=`echo $@ | awk '{print $1}'`;
userreq=`echo $@ | awk '{print $2}'`;
echo NoUser | grep $username
if [ $? -eq 0 ];
then
 exit
fi
echo admin | grep $username
if [ $? -eq 0 ];
then
 exit
fi


privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
myip=`/sbin/pcs resource show CC | grep Attrib | awk -F'ip=' '{print $2}' | awk '{print $1}'`
if [[ $contrun == 'true' ]]
then
/TopStor/UnixDelUserlocal $username $userreq
fi
cat /etc/passwd | grep $username
if [ $? -ne 0 ];
then
 /pace/etcddellocal.py $myip users $username 
fi
