#!/bin/bash
echo $@ > /root/unixchangeuser
export ETCDCTL_API=3
cd /TopStor
leaderip=`echo $@ | awk '{print $1}'`;
username=`echo $@ | awk '{print $2}'`;
usergroups=`echo $@ | awk  '{print $3}' | sed 's/groups//g' `;
userreq=`echo $@  | awk '{print $4}'`;
ischange=`echo $@  | awk '{print $5}'`;
pullsync=`echo $@  | awk '{print $6}'`;
stablegrp=""
privilege="Box_Users";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]];
then
	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq 
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -eq 0 ];
	then
	 	etcd=$leaderip
	else
		etcd=$myhostip
	fi
 #if a change happens before a user is created, no need to proceed, the script will be run again in the AddUser
 id $username
 if [ $? -ne 0 ];
 then
	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish $userreq 
	exit 
 fi
 echo 'NoUser' | grep $username
 if [ $? -ne 0 ];
 then
 	echo s$pullsync | grep pull 
 	if [ $? -ne 0 ];
 	then
  		docker exec etcdclient /TopStor/logmsg.py Unst1024 info $userreq $username
	fi
 fi
 echo $username | grep NoUser
 if [ $? -ne 0 ];
 then
  if [[ $usergroups == 'NoGroup' ]];
  then
   usermod -G '' $username
  else
   usermod -G '' $username
   usermod -G $usergroups $username
  fi
  usermod -a -G $username  $username
  cgrps=`/pace/etcdget.py $etcd usersigroup $username`
  cgrpsl=${#cgrps}
  while [ $cgrpsl  -gt 4 ];
  do
   l=`echo "${cgrps[@]}" | tail -1 `
   cgrps=`echo "${cgrps[@]}" | sed '$d'`
   cgrpsl=${#cgrps}
   cgrp=`echo $l | sed "s/('usersigroup\///g" | awk -F"'" '{print $1}' `  
   echo $usergroups | grep -w $cgrp  &>/dev/null
   if [ $? -ne 0 ];
   then
    usersall=`/pace/etcdget.py $etcd usersigroup/$cgrp`
    cusers=`echo $usersall | awk -F'/' '{print $3}'`
    cusersleft=`echo $usersall | cut -d/ -f1-2`
    cusersright=`echo $usersall | cut -d/ -f4-`
    newusers=`echo ${cusers} | sed "s/,$username//g" | sed "s/$username,//g" | sed "s/$username//g" `
    resusers=${#newusers}
    if [ $resusers -le 2 ];
    then
     newusers='NoUser'
    fi
    newop=$cusersleft'/'$newusers'/'$cusersright
    groupres=`echo ${newop} | sed "s/$username,//g" | sed "s/,$username//g" `
    echo to remove : $cgrp to be $groupres
 echo $etcd '333333333333333333333333333333333333333333333333333333333333333'
    /pace/etcdput.py $etcd usersigroup/$cgrp $groupres 
   else
    stablegrp=${stablegrp}${cgrp}',';
    echo to keep : $cgrp
   fi
  done
  echo the stable=$stablegrp
  usergroups=$usergroups','
  grpsl=` echo ${usergroups} | sed 's/,/ /g' | wc -w`
  while [ $grpsl -gt 0 ]; 
  do
   l=`echo $usergroups |  cut -d, -f 1`
   usergroups=`echo $usergroups | sed 's/ /,/g' | cut -d, -f2-`
   usergroups=$usergroups','
   grpsl=` echo ${usergroups} | sed 's/,/ /g' | wc -w`
   echo $l | grep -w $username
   if [ $? -eq 0 ];
   then
	continue
   fi
   echo usrgroups=$usergroups
   echo grpsl=$grpsl
   echo stablegrp=$stablegrp
   echo $l | grep -w NoGroup 
   if [ $? -ne 0 ];
   then
    echo 'kdsl' $stablegrp | grep -w $l 
    echo 'kdsl' $stablegrp | grep -w $l >/dev/null
    if [ $? -ne 0 ];
    then
     usersall=`/pace/etcdget.py $etcd usersigroup/$l`
     cusers=`echo $usersall | awk -F'/' '{print $3}'`
     cusersleft=`echo $usersall | cut -d/ -f1-2`
     cusersright=`echo $usersall | cut -d/ -f4-`
     echo $cusers | grep -w NoUser
     if [ $? -ne 0 ];
     then
      newusers=${cusers}','$username
      newop=$cusersleft'/'$newusers'/'$cusersright
      groupres=`echo ${newop}`
      echo appending $l to be $groupres
      /pace/etcdput.py $etcd usersigroup/$l $groupres 
     else 
      echo I am here: $username
      newusers=$username
      newop=$cusersleft'/'$newusers'/'$cusersright
      groupres=`echo ${newop}`
      echo adding $l to be $groupres

      /pace/etcdput.py $etcd usersigroup/$l $groupres 
     fi
    fi
   fi
  done
######### or else username=NoUser.. Remove all users form this usergroups
 else
  allusers=`/pace/etcdget.py $etcd usersigroup/$usergroups`
  usersall=`echo $allusers | awk -F'/' '{print $3}'`','
  usersl=` echo ${usersall} | sed 's/,/ /g' | wc -w`
  while [ $usersl -gt 0 ]; 
  do
   l=`echo $usersall |  cut -d, -f 1`
   usersall=`echo $usersall | sed 's/ /,/g' | cut -d, -f2-`
   usersall=$usersall','
   usersl=`echo ${usersall} | sed 's/,/ /g' | wc -w`
   echo l=$l
   echo usersall=$usersall
   echo usersl=$usersl
   gpasswd -d $l $usergroups
  done
   cusers=`echo $allusers | awk -F'/' '{print $3}'`
   cusersleft=`echo $allusers | cut -d/ -f1-2`
   cusersright=`echo $allusers | cut -d/ -f4-`
   newusers='NoUser'
   newop=$cusersleft'/'$newusers'/'$cusersright
   groupres=`echo ${newop}`
   /pace/etcdput.py $etcd usersigroup/$usergroups  $groupres 
 fi
 #/TopStor/broadcast.py UserChange /TopStor/pump.sh UnixChangeUser_sync -d$myhost $@ 
 echo 'NoUser' | grep $username
 if [ $? -ne 0 ];
 then
	echo s$pullsync | grep pull 
 	if [ $? -ne 0 ];
 	then
  		docker exec etcdclient /TopStor/logmsg.py Unsu1024 info $userreq $username
	fi
 fi
 echo dddddddddddddddddddddddddd $leader, $myhost
 echo $leader | grep $myhost
 if [ $? -eq 0 ];
 then
	stamp=`date +%s`;
	stamp=$((stamp+10))
	myscript=`basename "$0"`
	params=`echo $myscript $@ pull | sed 's\ \\_\g'`
	echo params=$params
	echo /pace/etcdput.py $etcd sync/UsrChange/$params/request/$myhost UsrChange_$stamp
	/TopStor/etcdput.py $etcd sync/UsrChange/$params/request/$myhost UsrChange_$stamp
	/TopStor/etcdput.py $etcd sync/UsrChange/$params/request UsrChange_$stamp
 fi
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` finish $userreq 
fi
