#!/bin/sh
cd /TopStor
export ETCDCTL_API=3
echo $@ > /root/voldeletes3

leaderip=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
volname=`echo $@ | awk '{print $3}'`;
pro=`echo $@ | awk '{print $4}'`;
userreq=`echo $@ | awk '{print $5}'`;
DG=$pDG;
privilege="CIFS";
contrun=`./privthis.sh $privilege $userreq`;

if [[ $contrun == 'true' ]]
then
 myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
 myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
 leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
 echo $leader | grep $myhost
 if [ $? -ne 0 ];
 then
  etcd=$myhostip
 else
  etcd=$leaderip
 fi

 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq
 ipaddr=`zfs get -H ip:addr $DG/$volname | awk '{print $3}'`
 ipsubnet=`zfs get -H ip:subnet $DG/$volname | awk '{print $3}'`
 /TopStor/VolumeDockerChange.py $ipaddr $ipsubnet S3
 /TopStor/SnapShotPeriodDelete $leaderip $volname $userreq
 /sbin/zfs unmount -f $DG/$volname
 /sbin/zfs destroy -rf $DG/$volname
 docker exec etcdclient /TopStor/etcdputlocal.py dirty/volume 0
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq
fi