#!/bin/sh
export ETCDCTL_API=3
cd /TopStor
echo $@ > /root/volcreatecifsdom
leaderip=`echo $@ | awk '{print $1}'`;
shortname=`echo $@ | awk '{print $3}'`;
nameid=$RANDOM$RANDOM
name=${shortname}_$nameid
pDG=`echo $@ | awk '{print $2}'`;
quota=`echo $@ | awk '{print $4}'`;
writev='DOMAIN'
ipaddr=`echo $@ | awk '{print $5}'`;
ipsubnet=`echo $@ | awk '{print $6}'`;
active=`echo $@ | awk '{print $7}'`;
userreq=` echo $@ | awk '{print $8}'`;
domname=` echo $@ | awk '{print $11}'`;
domsrvn=` echo $@ | awk '{print $12}'`;
domsrvi=` echo $@ | awk '{print $12}'`;
domadmin=` echo $@ | awk '{print $13}'`;
dompass=` echo $@ | awk '{print $14}'`;
DG=$pDG;
hi=`whoami`
echo start $hi $userreq > /root/volcreate
echo queuedrunning >> /root/volcreate
echo user=$userreq
privilege="CIFS";
./privthis.sh $privilege $userreq | grep true ;
if [ $? -eq 0 ];
then
	echo hhhhhhhhhhhhhhhhhhhh
	myhost=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternode`
	myhostip=`docker exec etcdclient /TopStor/etcdgetlocal.py clusternodeip`
	leader=`docker exec etcdclient /TopStor/etcdgetlocal.py leader`
	echo $leader | grep $myhost
	if [ $? -ne 0 ];
	then
 		etcd=$myhostip
	else
 		etcd=$leaderip
 	fi
	docker exec etcdclient /TopStor/logqueue.py `basename "$0"` running $userreq

 echo privileged $name >> /root/volcreate
 echo afterusersinfo >> /root/volcreate
 echo name=$name
 /sbin/zfs list | grep  "$shortname" 
 if [ $? -eq 0  ];
 then 
  docker exec etcdclient /TopStor/logmsg.py NFS1003 warning $userreq $DG/$name
 fi
 echo afterzfslist info $userreq $DG/$name >> /root/volcreateparam
 docker exec etcdclient /TopStor/logmsg.py NFS1004 info $userreq $DG/$name
 echo here4 >> /root/volcreate
 /sbin/zfs create -o overlay=on -o acltype=posixacl -o aclinherit=passthrough -o xattr=sa -o redundant_metadata=most -o atime=off -o quota=$quota -o dedup=on -o compression=lz4  $DG/$name  
 if [ $? -ne 0 ];
 then
  echo here5 >> /root/volcreate
  docker exec etcdclient /TopStor/logmsg.py NFS1006 error $userreq $DG/$name
  docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
  exit
 fi
 /sbin/zfs set prot:kind=CIFS_$domname $DG/$name
 /sbin/zfs set ip:addr=$ipaddr $DG/$name
 /sbin/zfs set ip:subnet=$ipsubnet $DG/$name
 /sbin/zfs set status:mount=$active $DG/$name
 echo /pace/etcdput.py $leaderip volumes/CIFS_$domname/$myhost/$DG/$name $DG/$name/no/yes/DOMAIN/administrator/yes/$ipaddr/$ipsubnet/$domname/$domsrvn/$domsrvi/$domadmin/$dompass/$active >> /root/volcreateparam
 ETCDCTL_API=3 /pace/etcdput.py $leaderip volumes/CIFS_$domname/$myhost/$DG/$name $DG/$name/no/yes/DOMAIN/administrator/yes/$ipaddr/$ipsubnet/$domname/$domsrvn/$domsrvi/$domadmin/$dompass/$active 
 #/pace/broadcasttolocal.py volumes/CIFS/$myhost/$DG/$name $DG/$name/no/yes/DOMAIN/administrator/yes/$ipaddr/$ipsubnet/$domname/$domsrvn/$domsrvi/$domadmin/$dompass/$active
 ./VolumeActivateCIFSdom $leaderip vol=$name user=$userreq
 /pace/putzpool.py $leaderip 
 /TopStor/SnapshotCreateHourlytrend $leaderip $DG $name 0 24 7 system 
 docker exec etcdclient /TopStor/logmsg.py NFS1007 info $userreq $DG/$name
fi
 docker exec etcdclient /TopStor/logqueue.py `basename "$0"` stop $userreq 
