#!/bin/sh
echo $@ >/root/volchangenfs
cd /TopStor
export ETCDCTL_API=3
perfmon=`cat /pacedata/perfmon`
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 docker exec etcdclient /TopStor/logqueue.py VolumeChangeNFS start system 
fi
echo hhhhhhhhhhhhhhhhhhhhhhhhhh
myhost=`hostname -s`
leaderip=`echo $@ | awk '{print $1}'`;
pDG=`echo $@ | awk '{print $2}'`;
name=`echo $@ | awk '{print $3}'`;
quota=`echo $@ | awk '{print $4}'`;
writev=`echo $@ | awk '{print $5}'`;
ipaddr=`echo $@ | awk '{print $6}'`;
ipsubnet=`echo $@ | awk '{print $7}'`;
active=`echo $@ | awk '{print $8}'`;
userreq=` echo $@ | awk '{print $10}'`;
DG=`echo $pDG `;
echo $@ > /root/VolChange
txtres='/TopStordata'`basename $0`'.txt'
rm -rf $txtres 2>/dev.null
privilege="NFS";
contrun=`./privthis.sh $privilege $userreq`;
if [[ $contrun == 'true' ]]
then
 docker exec etcdclient /TopStor/logmsg.py VolCst01 info $userreq $name
 older=`/pace/etcdget.py $leaderip volumes $name `
 oct1=`echo $ipaddr | awk -F'.' '{print $1}'`
 oct2=`echo $ipaddr | awk -F'.' '{print $2}'`
 oct3=`echo $ipaddr | awk -F'.' '{print $3}'`
 who=$oct1'.'$oct2'.'$oct3'.*'
 ETCDCTL_API=3 /pace/etcdput.py $leaderip volumes/NFS/$myhost/$DG/$name $DG/$name/$who/rw/sync/insecure/no_root_squash/no_all_squash/$writev/$ipaddr/$ipsubnet/$active
  stamp=`date +%s`
  leader=` ./etcdget.py $leaderip leader `
  /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request volumes_$stamp
  /pace/etcdput.py $leaderip sync/volumes/${DG}_$name/request/$leader volumes_$stamp
 oldipaddr=`zfs get -H ip:addr $DG/$name | awk '{print $3}'`
 oldipsubnet=`zfs get -H ip:subnet $DG/$name | awk '{print $3}'`
 sed -i "s/$oldipaddr/$ipaddr/g" /$DG/exports.$name
 sed -i "s/$oldipsubnet/$ipsubnet/g" /$DG/exports.$name
 /sbin/zfs set ip:addr=$ipaddr $DG/$name
 /sbin/zfs set ip:subnet=$ipsubnet $DG/$name
 /sbin/zfs set status:mount=$active $DG/$name
 docker rm -f NFS-$oldipaddr
 echo $older | grep -w $ipaddr/$ipsubnet
 if [ $? -ne 0 ];
 then 
  echo /TopStor/VolumeActivateNFS vol=$name user=$userreq
 fi
 docker exec etcdclient /TopStor/logmsg.py VolCsu01 info $userreq $name
fi;
 /pace/putzpool.py &
echo $perfmon | grep 1
if [ $? -eq 0 ]; then
 docker exec etcdclient /TopStor/logqueue.py VolumeChangeNFS finish system 
fi
